name: DevSecOps CI/CD Pipeline

on:
  push:
    branch: main


jobs:

  security-check:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false

    steps: 
    - name: checkout repository
      uses: actions/checkout@v2
    
    #Checking Code Quality 
    - name: code linting
      run: |
        pip install flake8
        flake8 

    - name: code quality analysis
      uses: github/codeql-action/init@v2
      with:
        languages: 'python'
        
    - name: autobuild codeql 
      uses: github/codeql-action/autobuild@v2

    - name: perform codeql analysis
      uses: github/codeql-action/analyze@v2
    
    # Scanning Secret Key 
    - name: gitleaks
      uses: gitleaks/gitleaks-action@v2
    
    # SAST 
    - name: bandit
      run: |
        pip install bandit
        bandit -r . 
  #build:
    #runs-on: ubuntu-latest
    #steps:
    
    #- name: docker build image
    #  run: |
    #    docker login -u enjangse -p ${{ secrets.DOCKER_HUB_PASSWORD }}
    #    docker build -t enjangse/devsecopsfastapi:latest .
    #    docker push enjangse/devsecopsfastapi:latest