name: DevSecOps CI/CD Pipeline

on:
  push:
    branch: main


jobs:

  security-check:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false

    steps: 
    - name: checkout repository
      uses: actions/checkout@v2

    - name: code linting
      run: |
        pip install flake8
        flake8 

    - name: code quality analysis
      uses: github/codeql-action/init@v2
      with:
        languages: 'python'
        
    - name: autobuild codeql 
      uses: github/codeql-action/autobuild@v2

    - name: perform codeql analysis
      uses: github/codeql-action/analyze@v2
    
    - name: scan code whisper
      run: |
        pip install whispers
        whispers_output=$(whispers .)
      # Check if there are any warnings in the output
        if [[ "$whispers_output" == *"Warning"* ]]; then
          echo "Whispers detected a password and marked it as a warning."
          echo "$whispers_output" >&2
          exit 1
        fi
    #- name: secret keys scanning
    #  run: |
    #    pip install detect-secrets
    #    detect-secrets scan --exclude-files .git
    #- name: secret keys scannning
    #  uses: gitleaks/gitleaks-action@v2

  #build:
    #runs-on: ubuntu-latest
    #steps:
    
    #- name: docker build image
    #  run: |
    #    docker login -u enjangse -p ${{ secrets.DOCKER_HUB_PASSWORD }}
    #    docker build -t enjangse/devsecopsfastapi:latest .
    #    docker push enjangse/devsecopsfastapi:latest